fix: use gender neutral german translations
ultical/ultical pull request #103
Opened 2023-01-27 11:52 UTC by vossmalte

2023-01-27 11:56 UTC, vossmalte reviewed
please check if this is wanted and double-check if no typo occurred (:

2023-01-27 12:04 UTC, bslbckr commented
Dear @vossmalte first of all: thanks for your effort and taking the initiative.

I'm sure it will clearly improve the current situation. I'll have a closer look to find any mistakes later.

2023-01-27 12:56 UTC, vossmalte commented
@bslbckr oh no. I just saw that the formatting was disrupted. I will fix that.

2023-01-27 19:37 UTC, vossmalte commented
@bslbckr now the format is not changed (it is quite diverse with spaces and tabs). Let me know if this PR needs improvement.

2023-01-27 20:12 UTC, bslbckr requested changes
Ich denke die genannten Punkte, sollten wir auch noch anpassen, dann haben wir am Ende einen ordentlichen und konsistenten Text. Ich helfe auch gerne bei Formulierungen

2023-01-27 20:12 UTC, bslbckr commented on backend/src/main/java/de/ultical/backend/jobs/DfvProfileLoader.java
> +                    String explainParagraph = "Die Gründe dafür können sein:\n\tDer:die Spieler:in wurde von seinem Verein noch nicht für das nächste Kalenderjahr gemeldet\n\tDer:die Spieler:in ist a
"wurde von seinem Verein" passt jetzt nicht mehr bzw immer noch nicht. Wenn wir den Text so bestehen lassen möchten, dann sehe ich drei Varianten:
- seinem/ihrem Verein
- vom meldenden Verein
- wurde noch nicht gemeldet (Verein streichen wir hier komplett)

Was denkt ihr?

2023-01-27 20:12 UTC, bslbckr commented on backend/src/main/java/de/ultical/backend/jobs/DfvProfileLoader.java
> +                    String explainParagraph = "Die Gründe dafür können sein:\n\tDer:die Spieler:in wurde von seinem Verein noch nicht für das nächste Kalenderjahr gemeldet\n\tDer:die Spieler:in ist a
Mit der Datenschutzerklärung haben wir ein analoges Problem

2023-01-27 20:12 UTC, bslbckr commented on web/i18n/texts-de.js
> +				playerBlocked: 'Der:die Spieler:in war Teil dieses Rosters während eines offiziellen Turniers. Er ist für diese Saison festgespielt und kann nicht entfernt werden.',
"Er ist für diese Saison" muss ebenfalls korrigiert werden

2023-01-27 20:12 UTC, bslbckr commented on web/i18n/texts-de.js
> +				playerWrongAge: 'Der:die Spieler:in ist aufgrund seines Alters in dieser Division in diesem Jahr nicht spielberechtigt. Ist diese Information fehlerhaft, wende dich an euren Vereinsadmin, um die
Hier passt "aufgrund seines Alters" nicht

2023-01-27 20:12 UTC, bslbckr commented on web/i18n/texts-de.js
> +				  idle: 'Der:die Spieler:in ist nicht spielberechtigt. Das liegt daran, dass er auf "ruht" gesetzt wurde in der Meldung.',
"dass er auf" sollte "dass sie/er auf" sein

2023-02-02 14:36 UTC, vossmalte commented on backend/src/main/java/de/ultical/backend/jobs/DfvProfileLoader.java
> +                    String explainParagraph = "Die Gründe dafür können sein:\n\tDer:die Spieler:in wurde von seinem Verein noch nicht für das nächste Kalenderjahr gemeldet\n\tDer:die Spieler:in ist a
ich denke 'seinem:ihrem' passt, die Information, dass es über den Verein läuft kann hilfreich sein.

2023-02-09 14:58 UTC, vossmalte commented
@bslbckr do you see any more phrases that I forgot? Thank you for being a good reviewer 👍 with eyes 👀  for details.

2023-02-11 11:04 UTC, merged

2023-02-11 11:05 UTC, bslbckr commented
@vossmalte thanks again for your effort, I just merged your PR.
@bastrapp could you please deploy an updated version?

2023-02-11 11:08 UTC, bastrapp commented
Thank you both. I will deploy the new version this weekend

Basil ***@***.***> schrieb am Sa., 11. Feb. 2023, 12:06:

> @vossmalte <https://github.com/vossmalte> thanks again for your effort, I
> just merged your PR.
> @bastrapp <https://github.com/bastrapp> could you please deploy an
> updated version?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ultical/ultical/pull/103#issuecomment-1426700194>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAQHYRWQRM7F3M5WFYFBACLWW5XB3ANCNFSM6AAAAAAUITMRNU>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>